---
# Prettier configuration
overrides:
    - files:
          - '**/*.*'
      options:
          printWidth: 160
    - files:
          - '**/*.xml'
      options:
          tabWidth: 4
          printWidth: 160
    - files:
          - '**/*.java'
      options:
          printWidth: 160
          tabWidth: 4
          useTabs: false
          trailingComma: none
          requirePragma: false
