name: CI - test and coverage

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: 'maven'

      - name: Test
        run: mvn verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Reporter
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report - ${{ matrix.os }}
          path: '**/surefire-reports/TEST*.xml'
          list-suites: 'failed'
          list-tests: 'failed'
          reporter: java-junit

      - name: Get coverage files
        run: |
          echo ::set-output name=COVERAGE_FILES::$(find **/jacoco*.xml -printf '%p,')
        id: coverage-files-generator

      - name: Codacy coverage reporter
        if: ${{ matrix.os != 'windows-latest' }}
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ steps.coverage-files-generator.COVERAGE_FILES }}
