name: CI - test and coverage

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up GraalVM 19
        uses: graalvm/setup-graalvm@v1
        with:
          version: "22.3.1"
          java-version: "19"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: "true"

      - name: Test
        run: mvn verify -Pnative
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Reporter
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report - ${{ matrix.os }}
          path: "**/surefire-reports/TEST*.xml"
          list-suites: "failed"
          list-tests: "failed"
          reporter: java-junit

      - name: Get coverage files
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          echo ::set-output name=COVERAGE_FILES::$(find **/jacoco*.xml -printf '%p,')
        id: coverage-files-generator

      - name: Codacy coverage reporter
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ steps.coverage-files-generator.COVERAGE_FILES }}
